#Generated Form Function
function GenerateForm {
########################################################################
# Code Generated By: SAPIEN Technologies PrimalForms (Community Edition) v1.0.9.0
# Generated On: 3/27/2017 11:26 AM
# Generated By: a_fedorenko
########################################################################

#region Import the Assemblies
[reflection.assembly]::loadwithpartialname("System.Drawing") | Out-Null
[reflection.assembly]::loadwithpartialname("System.Windows.Forms") | Out-Null
#endregion

#region Generated Form Objects
$form1 = New-Object System.Windows.Forms.Form
$btnSearch = New-Object System.Windows.Forms.Button
$btnNextUser = New-Object System.Windows.Forms.Button
$btnUnblock = New-Object System.Windows.Forms.Button
$btnClear = New-Object System.Windows.Forms.Button
$btnQuit = New-Object System.Windows.Forms.Button
$Status = New-Object System.Windows.Forms.GroupBox
$richtextboxStatus  = New-Object System.Windows.Forms.RichTextBox
$grpBoxUserInformation = New-Object System.Windows.Forms.GroupBox
$groupEmail = New-Object System.Windows.Forms.GroupBox
$textBoxEmail = New-Object System.Windows.Forms.TextBox
$grpBoxSD = New-Object System.Windows.Forms.GroupBox
$txtBoxEmployeeID = New-Object System.Windows.Forms.TextBox
$grpBoxName = New-Object System.Windows.Forms.GroupBox
$txtBoxname = New-Object System.Windows.Forms.TextBox
$InitialFormWindowState = New-Object System.Windows.Forms.FormWindowState
#endregion Generated Form Objects



function Enable-User {
[CmdletBinding(
   # ConfirmImpact = 'High',
    SupportsShouldProcess = $true
  

)]
    param(
        [parameter(Mandatory=$true,
        ValueFromPipeline=$true
        )]
        [string]$User
        
    )
    if ($PSCmdlet.ShouldProcess($user,"Enabling User")) {
        Enable-ADAccount -Identity $User -Server 'scedr07dc002.ce.rt.ru' 
    }
}




#----------------------------------------------
#Generated Event Script Blocks
#----------------------------------------------
#Provide Custom Code for events specified in PrimalForms.
$handler_btnSearch_Click= 
{
#TODO: Place custom script here
# Присваиваем переменной $Name значение из поля ФИО
    $Global:Name=$txtBoxName.Text;
    
    if($global:existADUsers=Get-ADUser -Properties EmployeeID,enabled,mail -Filter {(Enabled -eq $false)}  -SearchBase "dc=ce,dc=rt,dc=ru" -Server "scedr08dc001.ce.rt.ru" | where {$_.name -match $Global:Name}) `
        {
        $global:i =0
        foreach ($global:existAduser in $global:existADUsers){
               
        $richtextboxStatus.Text +="Найден пользователь $($global:existAduser.name).`nEmail $($global:existAduser.mail).`nEmployeeID $($global:existAduser.employeeid).`n`n";break
        $global:i ++
        }#EO Foreach
        }#EO IF
    
    
    
    
    
    else {$richtextboxStatus.Text +="Пользователь $Global:Name не найден.`n`n`n"}

#$count=$existADFIO.count










}

$handler_textBox2_TextChanged= 
{
#TODO: Place custom script here

}

$btnQuit_OnClick= 
{
#TODO: Place custom script here
$form1.Close()
}

$btnClear_OnClick= 
{
#TODO: Place custom script here
$txtBoxname.Text = $null
$textBoxEmail.Text = $null
$txtBoxEmployeeID.Text = $null
}

$btnUnblock_OnClick= 
{
#TODO: Place custom script here
$global:existAduser | Enable-User;
#$global:existAduser | Enable-User;
$richtextboxStatus.Text +="Пользователь $($global:existAduser.distinguishedname) разблокирован.`n";
}

$btnNextUser_OnClick= 
{
#TODO: Place custom script here

   

}

$OnLoadForm_StateCorrection=
{#Correct the initial state of the form to prevent the .Net maximized form issue
	$form1.WindowState = $InitialFormWindowState
}

#----------------------------------------------
#region Generated Form Code
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 472
$System_Drawing_Size.Width = 792
$form1.ClientSize = $System_Drawing_Size
$form1.DataBindings.DefaultDataSourceUpdateMode = 0
$form1.Name = "form1"
$form1.Text = "Разблокировать пользователя в CE.RT.RU"


$btnSearch.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 351
$System_Drawing_Point.Y = 437
$btnSearch.Location = $System_Drawing_Point
$btnSearch.Name = "btnSearch"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 75
$btnSearch.Size = $System_Drawing_Size
$btnSearch.TabIndex = 6
$btnSearch.Text = "Поиск"
$btnSearch.UseVisualStyleBackColor = $True
$btnSearch.add_Click($handler_btnSearch_Click)

$form1.Controls.Add($btnSearch)


$btnNextUser.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 540
$System_Drawing_Point.Y = 437
$btnNextUser.Location = $System_Drawing_Point
$btnNextUser.Name = "btnNextUser"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 94
$btnNextUser.Size = $System_Drawing_Size
$btnNextUser.TabIndex = 5
$btnNextUser.Text = "Следующая УЗ"
$btnNextUser.UseVisualStyleBackColor = $True
$btnNextUser.add_Click($btnNextUser_OnClick)

$form1.Controls.Add($btnNextUser)


$btnUnblock.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 430
$System_Drawing_Point.Y = 437
$btnUnblock.Location = $System_Drawing_Point
$btnUnblock.Name = "btnUnblock"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 104
$btnUnblock.Size = $System_Drawing_Size
$btnUnblock.TabIndex = 4
$btnUnblock.Text = "Разблокировать"
$btnUnblock.UseVisualStyleBackColor = $True
$btnUnblock.add_Click($btnUnblock_OnClick)

$form1.Controls.Add($btnUnblock)


$btnClear.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 640
$System_Drawing_Point.Y = 437
$btnClear.Location = $System_Drawing_Point
$btnClear.Name = "btnClear"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 68
$btnClear.Size = $System_Drawing_Size
$btnClear.TabIndex = 3
$btnClear.Text = "Очистить"
$btnClear.UseVisualStyleBackColor = $True
$btnClear.add_Click($btnClear_OnClick)

$form1.Controls.Add($btnClear)


$btnQuit.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 714
$System_Drawing_Point.Y = 437
$btnQuit.Location = $System_Drawing_Point
$btnQuit.Name = "btnQuit"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 66
$btnQuit.Size = $System_Drawing_Size
$btnQuit.TabIndex = 2
$btnQuit.Text = "Выход"
$btnQuit.UseVisualStyleBackColor = $True
$btnQuit.add_Click($btnQuit_OnClick)

$form1.Controls.Add($btnQuit)


$Status.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 345
$System_Drawing_Point.Y = 1
$Status.Location = $System_Drawing_Point
$Status.Name = "Status"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 425
$System_Drawing_Size.Width = 435
$Status.Size = $System_Drawing_Size
$Status.TabIndex = 1
$Status.TabStop = $False
$Status.Text = "Статус операции"

$form1.Controls.Add($Status)
$richtextboxStatus.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 6
$System_Drawing_Point.Y = 19
$richtextboxStatus.Location = $System_Drawing_Point
$richtextboxStatus.Name = "richtextboxStatus "
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 400
$System_Drawing_Size.Width = 423
$richtextboxStatus.Size = $System_Drawing_Size
$richtextboxStatus.TabIndex = 0
$richtextboxStatus.Text = ""

$Status.Controls.Add($richtextboxStatus )



$grpBoxUserInformation.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 12
$System_Drawing_Point.Y = 1
$grpBoxUserInformation.Location = $System_Drawing_Point
$grpBoxUserInformation.Name = "grpBoxUserInformation"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 425
$System_Drawing_Size.Width = 327
$grpBoxUserInformation.Size = $System_Drawing_Size
$grpBoxUserInformation.TabIndex = 0
$grpBoxUserInformation.TabStop = $False
$grpBoxUserInformation.Text = "Информация о пользователе"

$form1.Controls.Add($grpBoxUserInformation)

$groupEmail.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 15
$System_Drawing_Point.Y = 191
$groupEmail.Location = $System_Drawing_Point
$groupEmail.Name = "groupEmail"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 53
$System_Drawing_Size.Width = 290
$groupEmail.Size = $System_Drawing_Size
$groupEmail.TabIndex = 2
$groupEmail.TabStop = $False
$groupEmail.Text = "E-Mail"
$groupEmail.Visible = $False

$grpBoxUserInformation.Controls.Add($groupEmail)
$textBoxEmail.DataBindings.DefaultDataSourceUpdateMode = 0
$textBoxEmail.Enabled = $False
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 7
$System_Drawing_Point.Y = 20
$textBoxEmail.Location = $System_Drawing_Point
$textBoxEmail.Name = "textBoxEmail"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 20
$System_Drawing_Size.Width = 270
$textBoxEmail.Size = $System_Drawing_Size
$textBoxEmail.TabIndex = 0

$groupEmail.Controls.Add($textBoxEmail)



$grpBoxSD.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 15
$System_Drawing_Point.Y = 118
$grpBoxSD.Location = $System_Drawing_Point
$grpBoxSD.Name = "grpBoxSD"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 53
$System_Drawing_Size.Width = 290
$grpBoxSD.Size = $System_Drawing_Size
$grpBoxSD.TabIndex = 1
$grpBoxSD.TabStop = $False
$grpBoxSD.Text = "EmployeeID"
$grpBoxSD.Visible = $False

$grpBoxUserInformation.Controls.Add($grpBoxSD)
$txtBoxEmployeeID.DataBindings.DefaultDataSourceUpdateMode = 0
$txtBoxEmployeeID.Enabled = $False
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 7
$System_Drawing_Point.Y = 20
$txtBoxEmployeeID.Location = $System_Drawing_Point
$txtBoxEmployeeID.Name = "txtBoxEmployeeID"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 20
$System_Drawing_Size.Width = 270
$txtBoxEmployeeID.Size = $System_Drawing_Size
$txtBoxEmployeeID.TabIndex = 0
$txtBoxEmployeeID.add_TextChanged($handler_textBox2_TextChanged)

$grpBoxSD.Controls.Add($txtBoxEmployeeID)



$grpBoxName.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 15
$System_Drawing_Point.Y = 44
$grpBoxName.Location = $System_Drawing_Point
$grpBoxName.Name = "grpBoxName"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 53
$System_Drawing_Size.Width = 290
$grpBoxName.Size = $System_Drawing_Size
$grpBoxName.TabIndex = 0
$grpBoxName.TabStop = $False
$grpBoxName.Text = "ФИО"

$grpBoxUserInformation.Controls.Add($grpBoxName)
$txtBoxname.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 7
$System_Drawing_Point.Y = 20
$txtBoxname.Location = $System_Drawing_Point
$txtBoxname.Name = "txtBoxname"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 20
$System_Drawing_Size.Width = 270
$txtBoxname.Size = $System_Drawing_Size
$txtBoxname.TabIndex = 0

$grpBoxName.Controls.Add($txtBoxname)



#endregion Generated Form Code

#Save the initial state of the form
$InitialFormWindowState = $form1.WindowState
#Init the OnLoad event to correct the initial state of the form
$form1.add_Load($OnLoadForm_StateCorrection)
#Show the Form
$form1.ShowDialog()| Out-Null

} #End Function

#Call the Function
GenerateForm
